### ISSUE TITLE
Screen recording Audio Sync issue

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#224]
I have tried recording google meet calls with it. In the beginning, audio and video remain in sync but after some time, the audio goes out of sync. Mostly Audio is ahead of the video.

These are the options that I use for recording

```
RecorderOptions.OutputOptions.RecorderMode = RecorderMode.Video;

RecorderOptions.VideoEncoderOptions.Framerate = 30;
RecorderOptions.VideoEncoderOptions.IsFixedFramerate = true;
RecorderOptions.VideoEncoderOptions.Quality = 80;
RecorderOptions.VideoEncoderOptions.Encoder = new H264VideoEncoder
{
	BitrateMode = H264BitrateControlMode.Quality,
	EncoderProfile = H264Profile.High
};

bool AudioEnabled = AudioDeviceComboBox.SelectedItem != null || SystemAudioDeviceComboBox.SelectedItem != null;
RecorderOptions.AudioOptions.IsAudioEnabled = true;
RecorderOptions.AudioOptions.IsInputDeviceEnabled = true;
RecorderOptions.AudioOptions.IsOutputDeviceEnabled = true;
RecorderOptions.AudioOptions.AudioInputDevice = (AudioDeviceComboBox.SelectedItem as AudioDevice).DeviceName;
RecorderOptions.AudioOptions.AudioOutputDevice = (SystemAudioDeviceComboBox.SelectedItem as AudioDevice).DeviceName;
RecorderOptions.AudioOptions.InputVolume = 1;
RecorderOptions.AudioOptions.OutputVolume = 1;

RecorderOptions.MouseOptions.IsMousePointerEnabled = true;

RecorderOptions.SourceOptions.RecordingSources = new List<RecordingSourceBase>
	{
		new DisplayRecordingSource(monitor)
		{
			OutputSize = monitor.OutputSize,
			Position = monitor.Position,
			RecorderApi = RecorderApi.WindowsGraphicsCapture,
			IsBorderRequired = false
		}
	};
}
```

**Comment by sskodje** [comment]
Was this with one of the releases, or compiled from the main branch? I pushed some fixes for audio drift issues a few days ago, but haven't made a new release yet.

**Comment by ranwer-dev** [comment]
Yeah, I noticed that recent commit. I was using latest branch code.

**Comment by sskodje** [comment]
Do you know the sample rate and bit rate of your microphone and output device? I'm guessing it has to be something about that, as i'm unable to reproduce.

**Comment by ranwer-dev** [comment]
I was using a USB mic 
![image](https://user-images.githubusercontent.com/92986100/214946058-2d9bbda4-4007-4f16-b895-7ecaaee44b67.png)

And Bluetooth headphone
![image](https://user-images.githubusercontent.com/92986100/214946369-bfa9c4d3-cb23-4bd6-b094-3ba0e27858ba.png)

But I have experienced this out-of-sync issue with simple wired hands-free too when I was not recording System Audio.

**Comment by sskodje** [comment]
Thanks, that's very helpful.

**Comment by ranwer-dev** [comment]
Were you able to reproduce/fix this?

**Comment by sskodje** [comment]
Unfortunately i wasn't able to reproduce it on any of my hardware, so the issue is kind of stuck.

**Comment by SID9-HoneyBee** [comment]
I have a similar issue. Could this issue have been resolved?
For the first 5 minutes after recording, the video and audio input are in sync.
However, as the recording continues, it is out of sync.
I am using version 3.1.2.

**Comment by sskodje** [comment]
I fixed some audio drift issues in version 5.2.0. You see if it fixes your issues.

https://github.com/sskodje/ScreenRecorderLib/releases/tag/v5.2.0

**Comment by ranwer-dev** [comment]
No, the issue is still there. It goes fine for the first few minutes, but later System's Audio gets delayed from the video.

> I fixed some audio drift issues in version 5.2.0. You see if it fixes your issues.
> 
> https://github.com/sskodje/ScreenRecorderLib/releases/tag/v5.2.0

**Comment by SID9-HoneyBee** [comment]
> I fixed some audio drift issues in version 5.2.0. You see if it fixes your issues.
> 
> https://github.com/sskodje/ScreenRecorderLib/releases/tag/v5.2.0

I was afraid to migrate to version 5 while using 3.1.2.
But I got it working yesterday.
As a result of testing by applying version 5.2.0, it is confirmed that the audio drift issue has been resolved.
Let's do a little more testing.
Thank you very much.

I would like to ask an additional question regarding WebCam Overlay.

**Comment by ranwer-dev** [comment]
> As a result of testing by applying version 5.2.0, it is confirmed that the audio drift issue has been resolved.

@SID9-HoneyBee your issue was with microphone audio or System Audio? My System audio issue is still there.

**Comment by SID9-HoneyBee** [comment]
> > As a result of testing by applying version 5.2.0, it is confirmed that the audio drift issue has been resolved.
> 
> @SID9-HoneyBee your issue was with microphone audio or System Audio? My System audio issue is still there.

Haven't tested in many environments. However, in testing in four environments, all out-of-sync issues were resolved.

Migrated to version 5.2.0. That's it.

**Comment by ranwer-dev** [comment]
@sskodje, this issue is still reproducible in version 6.6.0
