### ISSUE TITLE
Out of memory exception when running unit tests

### ISSUE THREAD

**Issue by sskodje** [sskodje/ScreenRecorderLib#51]
Yes the tests run into an out of memory exception. I tried to figure out why. The only thing I found is that the refcount for D3D objects is counting up.

```MF
MF shut down!
D3D11 WARNING: Live ID3D11Device at 0x094FCD2C, Refcount: 23 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
```

Did these unit tests ever work?

_Originally posted by @hakito in https://github.com/sskodje/ScreenRecorderLib/pull/50#issuecomment-594100220_

**Comment by hakito** [comment]
I tried the unit tests on another PC and they were working properly. I'll try again later on the other one.

**Comment by hakito** [comment]
I could again reproduce the memory problem on my other PC. In this PC I have 2 GPUs and 3 Screens. I reduced it to one Display and with this Setup the problem didn't come up:

```
MF shut down!
D3D11 WARNING: Live ID3D11Device at 0x110D8B0C, Refcount: 2 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
```

So it seems to be related to multiple display adapters

**Comment by sskodje** [comment]
Interesting. What are the two different GPU's you have?

**Comment by sskodje** [comment]
I fixed an issue that could cause sink writer to not be released at 872f9a0e7759f3931bb9df4051a9e01bde20d0c6. Can  you see if this fixes the problem?

By the way, the warning that says Live ID3D11Device at 0x110D8B0C, Refcount: 2 is normal. Those are references from the debug layer itself, which is not released until after it prints the live objects obviously. If there are leaked elements, it will also print in the debug output when you close the application.

**Comment by hakito** [comment]
No that didn't fix the problem. However [I isolated the line that's incrementing the ref count of the pDevice](https://github.com/sskodje/ScreenRecorderLib/blob/872f9a0e7759f3931bb9df4051a9e01bde20d0c6/ScreenRecorderLib/internal_recorder.cpp#L659). 

I'll investiagate why this happens only on this computer.

**Comment by hakito** [comment]
Ok, now I added a logging of the ref count on almost any line. And the weird thing is that the ref count **incremented** after [this line](https://github.com/sskodje/ScreenRecorderLib/blob/f577fd5f5a5bf16967d983d8e7b13467ccba42c1/ScreenRecorderLib/internal_recorder.cpp#L737´).

On the other machine it didn't increment here. I think this can only mean the increment happens on another thread?!? I suspect the sinkwriter?

**Comment by sskodje** [comment]
That's very probable. The sink writer works asyncronusly, so it just queues up frames to process and releases them after. If the sink writer finalizes without errors, i have no idea how to debug that.

I'll update nuget later tonight.

**Comment by hakito** [comment]
I think using a proxy to track the AddRef and Release calls per thread could help here

**Comment by hakito** [comment]
I really tried hard to figure out whats the cause for the memory leak.

![image](https://user-images.githubusercontent.com/320853/76286010-63b0a880-62a1-11ea-85a7-03ae5220065d.png)
Both 50runs have the same footprint.

Also with the proxy I couldn't figure out what's holding the resources. Some of the com references to the device are created internally from MF, so I couldn't track those AddRef() and Release() calls. I am not an expert in memory debugging. 

![image](https://user-images.githubusercontent.com/320853/76286685-09b0e280-62a3-11ea-9241-7be5068d21ab.png)
When creating two mem snapshots I cannot see whats consuming that much memory.
![image](https://user-images.githubusercontent.com/320853/76286763-35cc6380-62a3-11ea-98c3-89392ddcc934.png)

The best way I could reproduce the error on all my machines so far was to run the tests via RDP.

**Comment by sskodje** [comment]
Is the issue only present with hardware encoding on?

**Comment by hakito** [comment]
Yes you are right. Before reading your comment I had already the same Idea and tried it without the hardware encoding and had no issues.

```c++
RETURN_ON_BAD_HR(pAttributes->SetUINT32(MF_READWRITE_ENABLE_HARDWARE_TRANSFORMS, false));
```

But what I also tried is [creating the ID3D11Device and context only once](https://github.com/hakito/ScreenRecorderLib/commit/6db9075f2d49241a588dc709a17ceb2185d29bd0). I don't know if this is a valid solution but now the _Run50RecordingsTestWithOneInstance_ completes (with hardware encoding enabled) and shows an interesting memory footprint.

![image](https://user-images.githubusercontent.com/320853/76393389-beb2d000-6373-11ea-8311-14ae8035df9f.png)

Of course _Run50RecordingsTestWithDifferentInstances_ still runs out of memory.

**Comment by sskodje** [comment]
It makes sense, since the encoder seems to error out without cleaning up the resources. Of course it still leaks, but now it leaks 1 instance instead of 50, so it is just hiding the symptoms. 

There are some known issues with media foundation and multi-gpu systems. By [following these steps](https://answers.microsoft.com/en-us/windows/forum/all/select-gpu-to-use-by-specific-applications/eb671f52-5c24-428d-a7a0-02a36e91ee2f) you can choose what graphics card an application will use. Perhaps it will help narrow it down.

**Comment by hakito** [comment]
I am pretty sure that it's using the nvidia card. I think I've seen an nvenc.dll when examining the memory issues.

**Comment by sskodje** [comment]
And is it working if you are configuring it to use the other card?

**Comment by hakito** [comment]
It's even worse. When switching to the other GPU

![image](https://user-images.githubusercontent.com/320853/76439096-2c82ea00-63bc-11ea-9f81-5c6e87d2e250.png)

```
Error: RETURN_ON_BAD_HR: The specified device interface or feature level is not supported on this system.
```

**Comment by sskodje** [comment]
Something is borked on your system i think.  Intel HD graphics 530 should be very well supported for hardware video encoding with Intel Quicksync.

Can you download the tool from [here](https://matthewvaneerde.wordpress.com/2010/05/03/how-to-enumerate-media-foundation-transforms-on-your-system/) and check what is available on your system?

**Comment by hakito** [comment]
This was a beginners mistake. I upgraded the nvidia drivers and now the tests work. 

Still when using _Power saving_ mode I get the error from above.

But when disabling the nvidia card in device manager the tests work again. And I also checked that it's using hardware encoding of the Intel GPU in the task manager.

So I think this ticket can be closed.

For the records:

- Broken driver version was 26.21.14.4166 (Game Ready Driver 441.87).
- Fixed nvidia issue 2805384 in [Game Ready Driver 442.19 ](http://us.download.nvidia.com/Windows/442.19/442.19-win10-win8-win7-release-notes.pdf)
