### ISSUE TITLE
Write access violation in LoopbackCaptureThreadFunction

### ISSUE THREAD

**Issue by ZbigniewNastalski** [sskodje/ScreenRecorderLib#94]
Hi, after integrating ScreenRecorderLib my program started crashing with access violation exception. In my program I am following TestApp example and create and dispose the recorder for every new recording file.

I was able to reproduce the crash in the TestApp by starting and stopping recordings in quick succession.
![Screenshot](https://user-images.githubusercontent.com/52514021/95837692-9c12ea80-0d8c-11eb-86e9-5e7eb08c4020.PNG)

Hopefully this debugger screenshot will tell you more than me. What seems suspicious is that m_IsDestructed==true in the capture object and pArgs->pCaptureInstance is null.

Please help, 
Warm Regards
Zee

**Comment by ZeeNastalski** [comment]
I've narrowed this down a bit. It only crashes if the input and output devices are set explicitly. The following modification to the unit test does reliably reproduce the crash on my machine:

`        [TestMethod]
        public void Run50RecordingsTestWithDifferentInstances()
        {
            int i = 0;
            for (i = 0; i < 50; i++)
            {
                var inputDevice = Recorder.GetSystemAudioDevices(AudioDeviceSource.InputDevices).FirstOrDefault();
                var outputDevice = Recorder.GetSystemAudioDevices(AudioDeviceSource.OutputDevices).FirstOrDefault();

                using (Stream outStream = new MemoryStream())
                {
                    RecorderOptions options = new RecorderOptions();
                    options.VideoOptions = new VideoOptions
                    {
                        BitrateMode = BitrateControlMode.CBR,
                        Bitrate = 3000 * 1000,
                        Framerate = 30,
                    };
                    options.AudioOptions = new AudioOptions
                    {
                        IsAudioEnabled = true, 
                        IsOutputDeviceEnabled = true,
                        IsInputDeviceEnabled = true,

                        // comment those two lines out and the lib stops crashing
                        AudioInputDevice = inputDevice.Key, 
                        AudioOutputDevice = outputDevice.Key
                    };
                    
                    using (var rec = Recorder.CreateRecorder(options))
                    {
                        string error = "";
                        bool isError = false;
                        bool isComplete = false;
                        ManualResetEvent resetEvent = new ManualResetEvent(false);
                        rec.OnRecordingComplete += (s, args) =>
                        {
                            isComplete = true;
                            resetEvent.Set();
                        };
                        rec.OnRecordingFailed += (s, args) =>
                        {
                            isError = true;
                            error = args.Error;
                            resetEvent.Set();
                        };

                        rec.Record(outStream);
                        Thread.Sleep(1000);
                        rec.Stop();

                        Assert.IsTrue(resetEvent.WaitOne(5000), $"[{i}] Recording finalize timed out");
                        Assert.IsNotNull(outStream, $"[{i}] Outstream is null");
                        Assert.IsFalse(isError, $"[{i}] Recording error: " + error);
                        Assert.IsTrue(isComplete, $"[{i}] Recording not complete");
                        Assert.AreNotEqual(outStream.Length, 0, $"[{i}] Outstream length is 0");
                    }
                }
            }
        }`

**Comment by sskodje** [comment]
I think i've discovered the cause, thank you.

**Comment by sskodje** [comment]
Let me know if it's fixed with 355c3ddc9a1f6ea6515c4f2a817a9a0944ec9c58 :)

**Comment by ZeeNastalski** [comment]
I just tested and the unit test still crashes unfortunately. 

I think the problem might be that the recording is stopped before the LoopbackCaptureThreadFunction thread is started.

It might be that, loopback_capture which managed by unique_ptr which goes out of scope before LoopbackCaptureThreadFunction has time to start. That could explain why we say m_IsDestructed set to true.
![image](https://user-images.githubusercontent.com/7221987/96060531-785eba00-0edc-11eb-8a3f-072797e9b93c.png)


Thanks for your help and looking into it, isn't it a middle of the night in Norway?

**Comment by sskodje** [comment]
I keep a pretty weird day schedule, hehe.

I'm not happy at all with the code for audio recording, so i'm going to rewrite it in the near future. I'm not sure what is going wrong, but it is hard to understand the lifetime of the objects as it is now.

**Comment by ZeeNastalski** [comment]
Roger that. Thanks for your help, I'll keep investigating too.

**Comment by jpcanepa** [comment]
I've ran into this as well, but not deterministically. I wonder if it could be related to [this remark](https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nn-audioclient-iaudioclient#remarks) for the `IAudioClient`
